chore: fix broken imports from default->named and class->function commit conflicts (#110564)
This should fix CI.

```plaintext
/home/runner/work/sentry/sentry/static/app/views/settings/organizationIntegrations/pluginDeprecationAlert.tsx
Error:   60:1  error  We prefer named exports. Default exports are not allowed unless this file is lazy-imported  @sentry/no-default-export-components

/home/runner/work/sentry/sentry/static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
Error:   83:1  error  We prefer named exports. Default exports are not allowed unless this file is lazy-imported  @sentry/no-default-export-components

/home/runner/work/sentry/sentry/static/app/views/settings/project/projectKeys/details/keyStats.tsx
Error:   139:1  error  We prefer named exports. Default exports are not allowed unless this file is lazy-imported  @sentry/no-default-export-components
```